In [ ]:
import numpy as np

def calculate_mean_and_variance(data):
  mean = np.mean(data)
  variance = np.var(data, ddof=1)
  return mean, variance

data = np.array([0, 1, 2, 3, 4])
mean, variance = calculate_mean_and_variance(data)
print("Mean:", mean)
print("Variance:", variance)

Mean: 2.0
Variance: 2.5


In [ ]:
import numpy as np

def compute_covariance(x, y):
  if len(x) != len(y):
    raise ValueError("Give the same length vectors.")

  x_mean = np.mean(x)
  y_mean = np.mean(y)

  covariance = np.sum((x - x_mean) * (y - y_mean)) / (len(x) - 1)

  return covariance

x = np.array([1, 3, 5, 7, 9])
y = np.array([2, 4, 6, 8, 10])

covariance = compute_covariance(x, y)
print(covariance)

10.0


In [ ]:
import numpy as np

def compute_correlation(x, y):
  covariance = np.cov(x, y)[0, 1]
  variance_x = np.var(x)
  variance_y = np.var(y)
  correlation = covariance / np.sqrt(variance_x * variance_y)
  return correlation

x = np.array([1, 3, 7, 9, 11])
y = np.array([2, 4, 6, 8, 10])

correlation = compute_correlation(x, y)
print(correlation)

1.239050883952413


In [ ]:
import numpy as np

M = 5
N = 10
X = np.random.randn(M, N)

covariance_matrix = np.cov(X)
correlation_matrix = np.corrcoef(X)

print(covariance_matrix)
print(correlation_matrix)

[[ 0.66392053 -0.15330855 -0.31393988  0.07050263  0.00965261]
 [-0.15330855  0.32611754 -0.15252554  0.04936483  0.03927783]
 [-0.31393988 -0.15252554  0.86483385  0.10498058  0.08043601]
 [ 0.07050263  0.04936483  0.10498058  1.00548043  0.63274366]
 [ 0.00965261  0.03927783  0.08043601  0.63274366  1.87369274]]
[[ 1.         -0.32947408 -0.41430683  0.08629     0.00865441]
 [-0.32947408  1.         -0.28720312  0.08620724  0.05024713]
 [-0.41430683 -0.28720312  1.          0.11257859  0.06318805]
 [ 0.08629     0.08620724  0.11257859  1.          0.46099032]
 [ 0.00865441  0.05024713  0.06318805  0.46099032  1.        ]]
